apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: product-service
  namespace: {{ .Values.namespace }}
spec:
  template:
    metadata:
      name: product-service-v1
    spec:
      imagePullSecrets:
      - name: {{ .Values.secretName }}
      containers:
      - name: product
        image: iad.ocir.io/idmaqhrbiuyo/product:v0.9
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 2   
        resources:
          limits:
            cpu:  {{ .Values.limitCPU }}
            memory:  {{ .Values.limitMemory }}
          requests:
            cpu:  {{ .Values.requestCPU }}
            memory:  {{ .Values.requestMemory }}